"use client";
import {useMemo,useState} from "react";import {QirNode,QirEdge,domainOf,displayName} from "../lib/qir";
const labels:Record<string,string>={all:"All",kubernetes:"Kubernetes",containers:"Containers",cicd:"CI / CD",terraform:"Terraform",api:"APIs",data:"Data",other:"Other"};
export function ArchitectureExplorer({nodes,edges}:{nodes:QirNode[];edges:QirEdge[]}){
 const all=nodes.filter(n=>n.type!=="repository"),[domain,setDomain]=useState("all"),[selected,setSelected]=useState<QirNode|null>(null),[query,setQuery]=useState(""),[scale,setScale]=useState(1);
 const domains=["all",...Array.from(new Set(all.map(domainOf)))];
 const scoped=useMemo(()=>all.filter(n=>(domain==="all"||domainOf(n)===domain)&&(!query||displayName(n).toLowerCase().includes(query.toLowerCase())||n.type.toLowerCase().includes(query.toLowerCase()))),[all,domain,query]);
 const shown=scoped.slice(0,48),cols=Math.max(3,Math.ceil(Math.sqrt(shown.length*1.8))),w=Math.max(1000,cols*220+80),rows=Math.ceil(shown.length/cols),h=Math.max(520,rows*110+100);
 const pos=new Map(shown.map((n,i)=>[n.id,{x:120+(i%cols)*220,y:90+Math.floor(i/cols)*110}]));
 const visible=edges.filter(e=>pos.has(e.from)&&pos.has(e.to));const related=selected?edges.filter(e=>e.from===selected.id||e.to===selected.id):[];
 return <section className="panel graphPanel"><div className="panelHead"><div><span className="eyebrow">QIR KNOWLEDGE GRAPH</span><h2>Architecture Explorer</h2></div><div className="graphTools"><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search components…"/><button onClick={()=>setScale(v=>Math.min(1.6,v+.15))}>+</button><button onClick={()=>setScale(v=>Math.max(.55,v-.15))}>−</button><button onClick={()=>{setScale(1);setSelected(null);setQuery("")}}>Fit</button></div></div><div className="chips">{domains.map(d=><button className={domain===d?"chip active":"chip"} onClick={()=>{setDomain(d);setSelected(null)}} key={d}>{labels[d]||d}</button>)}</div><div className="explorerLayout"><div className="graphViewport"><div style={{width:w*scale,height:h*scale}}><svg viewBox={"0 0 "+w+" "+h} style={{width:w*scale,height:h*scale}}><defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10z" fill="currentColor"/></marker></defs>{visible.map((e,i)=>{const a=pos.get(e.from)!,b=pos.get(e.to)!;return <path key={i} d={"M"+a.x+" "+a.y+" C "+a.x+" "+((a.y+b.y)/2)+", "+b.x+" "+((a.y+b.y)/2)+", "+b.x+" "+b.y} className="edge" markerEnd="url(#a)"/>})}{shown.map(n=>{const p=pos.get(n.id)!,active=selected?.id===n.id;return <g key={n.id} onClick={()=>setSelected(n)} className="node" transform={"translate("+(p.x-85)+" "+(p.y-28)+")"}><rect width="170" height="56" rx="9" className={active?"nodeBox selected":"nodeBox"}/><text x="85" y="20" textAnchor="middle" className="nodeType">{n.type.replace("kubernetes-","k8s · ").replace("ci-","ci · ")}</text><text x="85" y="39" textAnchor="middle" className="nodeName">{displayName(n).slice(0,23)}</text></g>})}</svg></div></div><aside className="detailPanel">{selected?<><span className="eyebrow">COMPONENT</span><h3>{displayName(selected)}</h3><div className="detailType">{selected.type}</div><code>{selected.id}</code><div className="detailStats"><span><b>{related.filter(e=>e.to===selected.id).length}</b> incoming</span><span><b>{related.filter(e=>e.from===selected.id).length}</b> outgoing</span></div><h4>Relationships</h4>{related.slice(0,12).map((e,i)=><div className="miniEdge" key={i}><code>{e.relationship}</code><small>{e.from===selected.id?"→ "+e.to:"← "+e.from}</small></div>)}{selected.metadata&&<><h4>Evidence / metadata</h4><pre>{JSON.stringify(selected.metadata,null,2)}</pre></>}</>:<div className="emptyDetail"><strong>Select a component</strong><p>Inspect relationships, evidence and metadata without leaving the graph.</p></div>}</aside></div><small className="muted">Showing {shown.length} of {scoped.length} components · {visible.length} visible relationships · semantic overview</small></section>
}