package com.atlasiq.export;
import com.atlasiq.persistence.*;import com.atlasiq.qir.*;import jakarta.enterprise.context.ApplicationScoped;
import java.awt.*;import java.awt.image.BufferedImage;import java.io.*;import java.nio.charset.StandardCharsets;import javax.imageio.ImageIO;
import org.apache.pdfbox.pdmodel.*;import org.apache.pdfbox.pdmodel.font.PDType1Font;import org.apache.pdfbox.pdmodel.common.PDRectangle;
@ApplicationScoped public class ArchitectureExportService {
 private final AnalysisStore store;public ArchitectureExportService(AnalysisStore store){this.store=store;}private QirModel m(String id){return store.find(id).orElseThrow().model();}
 public String mermaid(String id){QirModel m=m(id);StringBuilder b=new StringBuilder("graph LR\n");for(QirNode n:m.nodes())b.append("  ").append(safe(n.id())).append("[\"").append(esc(n.name())).append("\"]\n");for(QirEdge e:m.edges())b.append("  ").append(safe(e.from())).append(" -->|").append(esc(e.relationship())).append("| ").append(safe(e.to())).append("\n");return b.toString();}
 public String plantUml(String id){QirModel m=m(id);StringBuilder b=new StringBuilder("@startuml\n");for(QirNode n:m.nodes())b.append("component \"").append(esc(n.name())).append("\" as ").append(safe(n.id())).append("\n");for(QirEdge e:m.edges())b.append(safe(e.from())).append(" --> ").append(safe(e.to())).append(" : ").append(esc(e.relationship())).append("\n");return b.append("@enduml\n").toString();}
 public String svg(String id){QirModel m=m(id);int h=Math.max(120,40+m.nodes().size()*28);StringBuilder b=new StringBuilder("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"1000\" height=\""+h+"\"><style>text{font-family:sans-serif;font-size:14px}</style>");int y=30;for(QirNode n:m.nodes()){b.append("<text x=\"20\" y=\"").append(y).append("\">").append(xml(n.type()+" · "+n.name())).append("</text>");y+=28;}return b.append("</svg>").toString();}
 public byte[] png(String id)throws IOException{QirModel m=m(id);int h=Math.max(120,40+m.nodes().size()*24);BufferedImage im=new BufferedImage(1200,h,BufferedImage.TYPE_INT_RGB);Graphics2D g=im.createGraphics();g.setColor(Color.WHITE);g.fillRect(0,0,1200,h);g.setColor(Color.BLACK);int y=28;for(QirNode n:m.nodes()){g.drawString(n.type()+" · "+n.name(),20,y);y+=24;}g.dispose();ByteArrayOutputStream o=new ByteArrayOutputStream();ImageIO.write(im,"png",o);return o.toByteArray();}
 public byte[] pdf(String id)throws IOException{QirModel m=m(id);try(PDDocument d=new PDDocument()){PDPage p=new PDPage(PDRectangle.A4);d.addPage(p);try(var s=new org.apache.pdfbox.pdmodel.PDPageContentStream(d,p)){s.beginText();s.setFont(PDType1Font.HELVETICA,10);s.newLineAtOffset(35,800);for(QirNode n:m.nodes().stream().limit(60).toList()){s.showText(ascii(n.type()+" - "+n.name()));s.newLineAtOffset(0,-12);}s.endText();}ByteArrayOutputStream o=new ByteArrayOutputStream();d.save(o);return o.toByteArray();}}
 private String safe(String x){return "n"+Integer.toUnsignedString(x.hashCode());}private String esc(String x){return x.replace("\"","'").replace("\n"," ");}private String xml(String x){return x.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}private String ascii(String x){return x.replaceAll("[^\\x20-\\x7E]","?");}
}
