package com.atlasiq.pr;
import jakarta.enterprise.context.ApplicationScoped;import java.io.*;import java.net.*;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.util.regex.*;
@ApplicationScoped public class GitHubPrProvider implements PrProvider {
 private final HttpClient http=HttpClient.newHttpClient();public String id(){return "github";}
 public PullRequestRef resolve(PrTarget t){try{String[] p=slug(t.repository());String api="https://api.github.com/repos/"+p[0]+"/"+p[1]+"/pulls/"+t.pullRequestId();String body=get(api,t.token());return new PullRequestRef(t.repository(),t.pullRequestId(),field(body,"base","sha"),field(body,"head","sha"),"https://github.com/"+p[0]+"/"+p[1]+"/pull/"+t.pullRequestId());}catch(Exception e){throw new IllegalStateException("unable to resolve GitHub PR",e);}}
 public void publishCheck(PrTarget t,PrIntelligenceReport r){try{String[] p=slug(t.repository());String conclusion=r.impact().score()>=70||!r.policyViolations().isEmpty()?"failure":"success";String json="{\"name\":\"AtlasIQ Architecture Check\",\"head_sha\":\""+r.headSha()+"\",\"status\":\"completed\",\"conclusion\":\""+conclusion+"\",\"output\":{\"title\":\"AtlasIQ Architecture Check\",\"summary\":\""+escape(PrReportRenderer.markdown(r))+"\"}}";post("https://api.github.com/repos/"+p[0]+"/"+p[1]+"/check-runs",t.token(),json);}catch(Exception e){throw new IllegalStateException("unable to publish GitHub check",e);}}
 public void publishComment(PrTarget t,String markdown){try{String[] p=slug(t.repository());post("https://api.github.com/repos/"+p[0]+"/"+p[1]+"/issues/"+t.pullRequestId()+"/comments",t.token(),"{\"body\":\""+escape(markdown)+"\"}");}catch(Exception e){throw new IllegalStateException("unable to publish GitHub comment",e);}}
 private String get(String u,String token)throws Exception{return send(u,token,null);}
 private void post(String u,String token,String json)throws Exception{send(u,token,json);}
 private String send(String u,String token,String json)throws Exception{HttpRequest.Builder b=HttpRequest.newBuilder(URI.create(u)).header("Accept","application/vnd.github+json").header("Authorization","Bearer "+token).header("X-GitHub-Api-Version","2022-11-28");b=json==null?b.GET():b.header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(json));var r=http.send(b.build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()/100!=2)throw new IOException("provider returned HTTP "+r.statusCode());return r.body();}
 private String[] slug(String repo){String x=repo.replace("https://github.com/","").replaceAll("/$","");String[] p=x.split("/");if(p.length!=2)throw new IllegalArgumentException("GitHub repository must be owner/repo or HTTPS URL");return p;}
 private String field(String json,String object,String key){Matcher m=Pattern.compile("\""+object+"\"\\s*:\\s*\\{.*?\""+key+"\"\\s*:\\s*\"([^\"]+)\"",Pattern.DOTALL).matcher(json);if(!m.find())throw new IllegalArgumentException("missing "+object+"."+key);return m.group(1);}
 private String escape(String s){return s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","");}
}