package com.atlasiq.pr;
import com.atlasiq.intelligence.*;import com.atlasiq.persistence.*;import com.atlasiq.qir.*;import com.atlasiq.scanner.*;import jakarta.enterprise.context.ApplicationScoped;import jakarta.enterprise.inject.Instance;import java.util.*;
@ApplicationScoped public class PrIntelligenceService {
 private final RepositoryScanner scanner;private final AnalysisStore store;private final ArchitectureDiffService diffs;private final PrChangeImpactService impacts;private final BlastRadiusService blast;private final ArchitecturePolicyEngine policies;private final Map<String,PrProvider> providers=new HashMap<>();
 public PrIntelligenceService(RepositoryScanner s,AnalysisStore st,ArchitectureDiffService d,PrChangeImpactService i,BlastRadiusService b,ArchitecturePolicyEngine p,Instance<PrProvider> ps){scanner=s;store=st;diffs=d;impacts=i;blast=b;policies=p;ps.forEach(x->providers.put(x.id(),x));}
 public PrIntelligenceReport analyze(PrProvider.PrTarget target){PrProvider provider=Optional.ofNullable(providers.get(target.provider().toLowerCase())).orElseThrow(()->new IllegalArgumentException("unsupported PR provider"));var ref=provider.resolve(target);var base=store.save(scanner.scan(new ScanRequest(ref.repository(),ref.baseSha(),null,target.token())));var head=store.save(scanner.scan(new ScanRequest(ref.repository(),ref.headSha(),null,target.token())));ArchitectureDiff d=diffs.compare(base.id(),head.id());PrChangeImpact impact=impacts.assess(base.id(),head.id());
  var security=d.addedFindings().stream().filter(f->"security".equalsIgnoreCase(f.category())).map(f->new PrIntelligenceReport.Delta("security",f.resourceId(),f.severity()+" - "+f.title())).toList();
  List<PrIntelligenceReport.Delta> dependencies=new ArrayList<>();for(QirEdge e:d.addedEdges())if(Set.of("depends_on","calls","consumes","produces","reads_from","writes_to").contains(e.relationship()))dependencies.add(new PrIntelligenceReport.Delta("dependency",e.from(),e.from()+" "+e.relationship()+" "+e.to()));
  List<PrIntelligenceReport.BreakingChange> breaking=new ArrayList<>();for(QirNode n:d.removedNodes()){if("api-endpoint".equals(n.type()))breaking.add(new PrIntelligenceReport.BreakingChange("api",n.id(),"API removed: "+n.name()));if("database-object".equals(n.type()))breaking.add(new PrIntelligenceReport.BreakingChange("database",n.id(),"Database object removed: "+n.name()));}
  List<PrIntelligenceReport.Blast> radius=new ArrayList<>();for(QirNode n:d.removedNodes().stream().limit(10).toList()){var x=blast.analyze(base.id(),n.id(),3);radius.add(new PrIntelligenceReport.Blast(n.id(),x.affectedNodes().size(),x.affectedNodes().stream().map(QirNode::id).toList()));}
  return new PrIntelligenceReport(provider.id(),ref.repository(),ref.number(),ref.baseSha(),ref.headSha(),base.id(),head.id(),d,impact,List.copyOf(security),List.copyOf(dependencies),List.copyOf(breaking),policies.evaluate(d),List.copyOf(radius));}
 public PrIntelligenceReport analyzeAndPublish(PrProvider.PrTarget target){var report=analyze(target);var p=providers.get(target.provider().toLowerCase());p.publishCheck(target,report);p.publishComment(target,PrReportRenderer.markdown(report));return report;}
}