package com.atlasiq.parser.platform;
import com.atlasiq.qir.*;import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;import jakarta.enterprise.context.ApplicationScoped;
import java.io.*;import java.nio.file.*;import java.util.*;import java.util.regex.*;import java.util.stream.Stream;
@ApplicationScoped public class PlatformDiscoveryParser {
 private static final Set<String> SKIP=Set.of(".git","target","build","dist","node_modules","vendor",".next");
 private static final Pattern TF=Pattern.compile("resource\\s+\"(aws_[^\"]+|azurerm_[^\"]+|google_[^\"]+)\"\\s+\"([^\"]+)\"");
 private static final Pattern OWNER=Pattern.compile("(?i)^(?:owner|team)\\s*[:=]\\s*([^#]+)$");
 private final ObjectMapper yaml=new ObjectMapper(new YAMLFactory());
 public List<QirNode> parse(Path root){Map<String,QirNode> out=new LinkedHashMap<>();
  try(Stream<Path>s=Files.walk(root,10)){s.filter(p->safe(root,p)).forEach(p->{String rel=root.relativize(p).toString().replace('\\','/');String name=p.getFileName().toString().toLowerCase();
   try{if(name.endsWith(".tf"))terraform(Files.readString(p),rel,out);if(name.equals("openapi.yaml")||name.equals("openapi.yml")||name.equals("swagger.yaml")||name.equals("swagger.yml")||name.equals("openapi.json")||name.equals("swagger.json"))api(p,rel,out);if(name.equals("asyncapi.yaml")||name.equals("asyncapi.yml")||name.equals("asyncapi.json"))async(p,rel,out);if(name.equals("catalog-info.yaml")||name.equals("catalog-info.yml")||name.equals("codeowners")||name.equals("ownership.yaml")||name.equals("ownership.yml"))ownership(p,rel,out);}catch(Exception ignored){}
  });}catch(IOException e){throw new IllegalStateException(e);}return List.copyOf(out.values());}
 private void terraform(String x,String file,Map<String,QirNode> out){Matcher m=TF.matcher(x);while(m.find()){String type=m.group(1),provider=type.startsWith("aws_")?"aws":type.startsWith("azurerm_")?"azure":"gcp";String id="cloud:"+provider+":"+type+":"+m.group(2);out.put(id,new QirNode(id,"cloud-resource",m.group(2),provider,Map.of("resourceType",type,"provider",provider,"evidenceFile",file)));}}
 private void api(Path p,String file,Map<String,QirNode> out)throws Exception{JsonNode d=read(p);String title=d.path("info").path("title").asText(p.getFileName().toString());String id="api-contract:"+file;out.put(id,new QirNode(id,"api-contract",title,"openapi",Map.of("specVersion",d.path("openapi").asText(d.path("swagger").asText()),"evidenceFile",file)));Iterator<String> paths=d.path("paths").fieldNames();while(paths.hasNext()){String path=paths.next();JsonNode ops=d.path("paths").path(path);ops.fieldNames().forEachRemaining(method->{if(Set.of("get","post","put","patch","delete","head","options").contains(method)){String eid=id+":"+method+":"+path;out.put(eid,new QirNode(eid,"api-endpoint",method.toUpperCase()+" "+path,"openapi",Map.of("contract",id,"evidenceFile",file)));}});}}
 private void async(Path p,String file,Map<String,QirNode> out)throws Exception{JsonNode d=read(p);String id="async-contract:"+file;out.put(id,new QirNode(id,"asyncapi-contract",d.path("info").path("title").asText(file),"asyncapi",Map.of("specVersion",d.path("asyncapi").asText(),"evidenceFile",file)));Iterator<String> channels=d.path("channels").fieldNames();while(channels.hasNext()){String ch=channels.next();String cid=id+":"+ch;out.put(cid,new QirNode(cid,"event-channel",ch,inferBroker(d),Map.of("contract",id,"evidenceFile",file)));}}
 private String inferBroker(JsonNode d){String s=d.toString().toLowerCase();return s.contains("kafka")?"kafka":s.contains("rabbit")||s.contains("amqp")?"rabbitmq":"event-broker";}
 private void ownership(Path p,String file,Map<String,QirNode> out)throws Exception{if(p.getFileName().toString().equalsIgnoreCase("CODEOWNERS")){for(String l:Files.readAllLines(p)){String t=l.trim();if(t.isEmpty()||t.startsWith("#"))continue;String[] a=t.split("\\s+");if(a.length>1)for(int i=1;i<a.length;i++)owner(a[i],file,out);}return;}JsonNode d=read(p);String owner=d.path("spec").path("owner").asText(d.path("owner").asText());if(!owner.isBlank())owner(owner,file,out);}
 private void owner(String owner,String file,Map<String,QirNode> out){String n=owner.trim();String id="owner:"+n.toLowerCase();out.put(id,new QirNode(id,"team",n,"ownership",Map.of("evidenceFile",file)));}
 private JsonNode read(Path p)throws Exception{return p.toString().endsWith(".json")?new ObjectMapper().readTree(p.toFile()):yaml.readTree(p.toFile());}
 private boolean safe(Path root,Path p){for(Path x:root.relativize(p))if(SKIP.contains(x.toString()))return false;return Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(p);}
}
