package com.atlasiq.enterprise;
import jakarta.enterprise.context.ApplicationScoped;import javax.sql.DataSource;import java.sql.*;import java.time.Instant;import java.util.*;
@ApplicationScoped public class EnterpriseStore {private final DataSource ds;public EnterpriseStore(DataSource d){ds=d;}
 public OrganizationService.Organization createOrg(String name){String id=UUID.randomUUID().toString();Instant now=Instant.now();exec("INSERT INTO atlasiq_organization(id,name,created_at) VALUES(?,?,?)",id,name,Timestamp.from(now));return new OrganizationService.Organization(id,name,now);}
 public OrganizationService.Workspace createWorkspace(String org,String name){String id=UUID.randomUUID().toString();Instant now=Instant.now();exec("INSERT INTO atlasiq_workspace(id,organization_id,name,created_at) VALUES(?,?,?,?)",id,org,name,Timestamp.from(now));return new OrganizationService.Workspace(id,org,name,now);}
 public void membership(String org,String ws,String subject,String role){exec("INSERT INTO atlasiq_membership(id,organization_id,workspace_id,subject,role,created_at) VALUES(?,?,?,?,?,?)",UUID.randomUUID().toString(),org,ws,subject,role,Timestamp.from(Instant.now()));}
 public Set<String> roles(String org,String ws,String subject){Set<String> out=new LinkedHashSet<>();try(Connection c=ds.getConnection();PreparedStatement p=c.prepareStatement("SELECT role FROM atlasiq_membership WHERE organization_id=? AND (workspace_id=? OR workspace_id IS NULL) AND subject=?")){p.setString(1,org);p.setString(2,ws);p.setString(3,subject);try(ResultSet r=p.executeQuery()){while(r.next())out.add(r.getString(1));}}catch(SQLException e){throw new IllegalStateException(e);}return out;}
 public List<OrganizationService.Workspace> workspaces(String org){List<OrganizationService.Workspace> out=new ArrayList<>();try(Connection c=ds.getConnection();PreparedStatement p=c.prepareStatement("SELECT id,name,created_at FROM atlasiq_workspace WHERE organization_id=? ORDER BY created_at")){p.setString(1,org);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new OrganizationService.Workspace(r.getString(1),org,r.getString(2),r.getTimestamp(3).toInstant()));}}catch(SQLException e){throw new IllegalStateException(e);}return out;}
 public void exec(String sql,Object...v){try(Connection c=ds.getConnection();PreparedStatement p=c.prepareStatement(sql)){for(int i=0;i<v.length;i++)p.setObject(i+1,v[i]);p.executeUpdate();}catch(SQLException e){throw new IllegalStateException(e);}}
}